project:
  type: website
  output-dir: docs

website:
  title: "Pedro Tabacof's blog"
  site-url: https://tabacof.github.io/
  description: "Pedro Tabacof's personal blog"
  twitter-card: true
  open-graph: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/tabacof/
      - icon: linkedin
        href: https://www.linkedin.com/in/tabacof/
      - icon: twitter
        href: https://twitter.com/PedroTabacof
format:
  html:
    theme: litera
    css: styles.css
