FROM public.ecr.aws/lambda/python:3.9.2023.03.15.15-x86_64 

# Install the function's dependencies using file requirements.txt
# from your project folder.

COPY requirements.txt  .
RUN  pip3 install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

# Copy function code
COPY predict_sklearn.py ${LAMBDA_TASK_ROOT}
COPY model.pickle ${LAMBDA_TASK_ROOT}

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "predict_sklearn.predict" ]